- name: variable
  hosts: localhost
  vars:
    course: "Ansible"
    trainer: "siva"
    duration: "130hrs"
  tasks:
  - name: print information
    ansible.builtin.debug:
     msg: "Hi, we are learning {{course}} from trainer {{trainer}},duration {{duration}}."
   