- name: variable
  hosts: localhost
  vars:
    course: "Terraform"
    trainer: "siva reddy"
    duration: "3.5 months"
  tasks:
  - name: print information
    vars:
      course: "Devops"
      ansible.builtin.debug:
      msg: "Hi, we are learning {{course}} from trainer {{trainer}},duration {{duration}}."
  - name: print inheritance information
    anisble.builtin.debug:
    msg: "Hi, we are learning {{course}} from trainer {{trainer}},duration {{duration}}."
    
