- name: check number
  hosts: localhost
  vars_prompt:
  - name: number
    prompt: please enter number
    private: no
  tasks: 
  - name: number is less than 10
    ansible.builtin.debug:
      msg: "Given number {{number}} is less than 10"
    when: number | int <10
    
  - name: number is greater than or equal 10
    ansible.builtin.debug:
      msg: "Given number {{number}} greater than or equal 10"
    when: number | int >=10