- name: default variable
  hosts: localhost
  tasks:
  - name: print default variable
    ansible.builtin.debug:
      msg: "Hello {{course | default('Ansible')}}"

- name: uppercase
  hosts: localhost
  vars:
    greetings: "hello good morning"
  tasks:
  - name: uppercase
    ansible.builtin.debug:
      msg: "{{greetings | upper }}"

- name: lower case
  hosts: localhost
  vars: 
    greetings: "HELLO GOOD AFTERNOON"
  tasks:
  - name: lower case
    ansible.builtin.debug:
      msg: "{{greetings | lower }}"

- name: duplicate values
  hosts: localhost
  vars:
    number: [1, 2, 3, 4, 5, 4, 3, 2, 2]
  tasks:
  - name: removing duplicate values
    ansible.builtin.debug:
      msg: "{{number | unique }}"

- name: min and max
  hosts: localhost
  vars:
    ages: [25, 67, 66,88,97]
  tasks:
  - name: min and max
    ansible.builtin.debug:
      msg: "min age: {{ages | min }}, max age: {{ages | max }}"
- name: convert dictonary into items/list
  hosts: localhost
  vars:
   my_dict:
     course: Ansible
     trainer: sivakumar
     duration: 130hr
  tasks:
  - name: before convert
    ansible.builtin.debug:
      msg: "{{my_dict}}"
  - name: before convert
    ansible.builtin.debug:
      msg: "{{my_dict | dict2items }}"

- name: convert items/list into dictonary
  hosts: localhost
  vars:
   my_items:
    - {'key': 'Course', 'value': 'Ansbile'}
    - {'key': 'Trainer', 'value': 'Sivakumar'}
    - {'key': 'Duration', 'value': '120hr'}
  tasks:
  - name: before convert
    ansible.builtin.debug:
      msg: "{{my_items}}"
  - name: before convert
    ansible.builtin.debug:
      msg: "{{my_items | items2dic }}"
