- name: install packages
  hosts: localhost
  become: yes
  tasks:
  - name: install packages
    ansible.builtiin.dnf:
    name: "{{item}}"
    state: latest
    loop:
    - mysql
    - nginx
    - postfix